---
- hosts: all
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    - name: Install base packages
      apt:
        name: ['mc','htop', 'sudo', 'ca-certificates', 'git', 'lsb-release', 'software-properties-common', 'nfs-common', 'net-tools']
        state: latest
